name: parteez
services:
  pz-proxy:
    image: traefik:v3.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      
    labels:
      - "traefik.enable=true"
    depends_on:
      pz-api:
        condition: service_started
      pz-db:
        condition: service_healthy
  
  pz-api:
    image: massand3r/parteez-api:latest
    ports:
      - 8080:8080
    depends_on:
      pz-db:
        condition: service_healthy

  pz-db:
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Uncomment to expose ports
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/pz-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  pz-queue:
    image: bitnami/kafka:latest
    restart: unless-stopped
    ports:
      - 9092:9092
    volumes:
      - ./docker/data/pz-queue-data:/bitnami/kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KAFKA_CLUSTER_ID: "KRaft-cluster-0x2f3a9c1d"
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@pz-queue:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://pz-queue:9090,EXTERNAL://${HOSTNAME:-127.0.0.1}:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  
  pz-queue-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      KAFKA_BROKERS: pz-queue:9090

volumes:
  pz-db-data:
    driver: local

secrets:
  cf_api_token:
    file: ./cf_api_token.txt
