DROP TABLE IF EXISTS event_genres;
DROP TABLE IF EXISTS event_promo;
DROP TABLE IF EXISTS event_tickets;
DROP TABLE IF EXISTS event_lineup;
DROP TABLE IF EXISTS venue_stages;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS venue;
DROP TABLE IF EXISTS artwork;

DROP INDEX IF EXISTS "index_event_date";
DROP INDEX IF EXISTS "index_event_public";

DROP TYPE IF EXISTS venue_type;



