DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS event_genres;
DROP TABLE IF EXISTS event_interests;
DROP TABLE IF EXISTS event_reviews;
DROP TABLE IF EXISTS event;
DROP TYPE IF EXISTS event_status;
DROP INDEX IF EXISTS event_starts_at_idx;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS location;
DROP TYPE IF EXISTS location_type;


